### PR TITLE
Fix property name truncation in getproperties()

### PR DESCRIPTION
**Pull request by urlicht**
Resolving issue #22

### CODE REVIEW

**Comment by bjarthur** [comment]
thanks for the contribution!  but, this used to not be a problem.  what is different do you think?

**Comment by urlicht** [comment]
I just checked, and the problem is julia version dependent. On v1.0.5, it functions fine as is, but the proposed fix is required for v1.2.0 or later. I won't be able to debug it to find the exact source at the moment, but perhaps some changes were made in julia ccall between v1.0.5 and v1.2.0?

**Comment by bjarthur** [comment]
`VERSION >= v"1.2" ? 15 : 9` maybe?

**Comment by urlicht** [comment]
I haven't had time to debug the problem, but I included your proposed version dependent change to the fix.

**Comment by bjarthur** [comment]
thanks!

**Pull request merged**
